### ISSUE TITLE
Test issue created from vscode.

### ISSUE THREAD

**Issue by isaacholt100** [isaacholt100/isaacholt#4]
test body

**Comment by MohitBansal321** [comment]
can you describe more

**Comment by isaacholt100** [comment]
Was testing the GitHub extension for VS code, not an actual issue haha.

**Comment by MohitBansal321** [comment]
haha ,okay I'm  just finding a good first issue

**Comment by isaacholt100** [comment]
Good first issue for this repo or first ever?

**Comment by MohitBansal321** [comment]
first ever
if you know some please mention here

**Comment by isaacholt100** [comment]
I have a few projects: [https://github.com/isaacholt100/bnum], [https://github.com/isaacholt100/MYB] and [https://github.com/isaacholt100/latin-grammar-test] if you want to have a look at the existing issues or create a new one.
